import { RefreshCw, ShieldCheck, Sparkles } from "lucide-react";

import type { RuntimeStatus } from "../../shared/types.js";

export type StartupScreenMode = "starting" | "indexing" | "missingCodex" | "error";

interface StartupScreenProps {
  mode: StartupScreenMode;
  status: RuntimeStatus | null;
  error: string | null;
  onRetry: () => void;
}

export function StartupScreen({ mode, status, error, onRetry }: StartupScreenProps) {
  const content = getStartupContent(mode, status, error);
  const retryVisible = mode === "missingCodex" || mode === "error";

  return (
    <main className="startup-screen">
      <section className="startup-panel" aria-live="polite">
        <div className={mode === "indexing" || mode === "starting" ? "startup-mark spinning" : "startup-mark"}>
          {mode === "missingCodex" ? <Sparkles size={24} /> : <ShieldCheck size={24} />}
        </div>
        <p className="startup-kicker">Codex Desktop Companion</p>
        <h1>{content.title}</h1>
        <p>{content.body}</p>
        <div className="startup-local-note">
          <ShieldCheck size={15} />
          <span>Completely local. No network connection is used for your library.</span>
        </div>
        {content.detail ? <small>{content.detail}</small> : null}
        {retryVisible ? (
          <button className="startup-retry" onClick={onRetry}>
            <RefreshCw size={16} />
            Retry
          </button>
        ) : null}
      </section>
    </main>
  );
}

function getStartupContent(
  mode: StartupScreenMode,
  status: RuntimeStatus | null,
  error: string | null
): { title: string; body: string; detail: string | null } {
  if (mode === "missingCodex") {
    return {
      title: "Codex Desktop data was not found",
      body: "CoMate is built specifically for images generated by the Codex desktop app.",
      detail: status
        ? `Expected local data under ${status.codexDesktop.codexRoot}`
        : "Open Codex Desktop and generate an image, then retry."
    };
  }

  if (mode === "error") {
    return {
      title: "The local library could not be indexed",
      body: "CoMate could not finish reading the Codex Desktop image library on this machine.",
      detail: error
    };
  }

  if (mode === "indexing") {
    return {
      title: "Building your local image library",
      body: "CoMate is scanning Codex Desktop images and linking them with session prompts.",
      detail: status?.indexing.indexed ? `${status.indexing.indexed} images indexed so far.` : null
    };
  }

  return {
    title: "Starting CoMate",
    body: "Preparing the private local gallery for Codex Desktop images.",
    detail: null
  };
}
